name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter

  #iCONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
 
#State Management
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Utility Packages
  http: ^1.5.0
  url_launcher: ^6.3.0
  logger: ^1.1.0
  intl: ^0.20.2 
  flutter_lints: ^5.0.0
 
  #Splash Screen
  flutter_splash_screen: ^3.0.0

  #State Management
  get : ^4.6.5
  get_storage: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
  
  fonts:
    - family: Poppins